<?php
$pages_ids = pages_group_ids();
$user = wp_get_current_user();

 ?>

<section class="tc-content <?php echo $_layout_class; ?>">
    <?php do_action( '__before_content' ); ?>
        <div class="entry-content">
            <div class="hentry">
            <?php
            if(isset($_POST['id_name']) && isset($_POST['id_mail'])){
                $args = array(
            		    'ID'         => $user->ID,
            		    'user_email' => esc_attr( $_POST['id_mail'] ),
            		    'user_login' => esc_attr( $_POST['id_mail'] ),
                    'display_name' => esc_attr($_POST['id_name'])
            		);
            		$error = wp_update_user( $args );

                if(is_wp_error( $error )) { die($error); }

                $birth = date_create_from_format('d/m/Y', get_the_author_meta('birthday', $user->ID));
                $birth = get_etaria_user($birth);
                update_user_meta($user->ID, 'fEtaria', $birth);
                if($birth !== 'adulto'){
                    update_user_meta($user->ID, 'responsavel', $_POST['id_responsavel']);
                }
                update_user_meta($user->ID, 'phone', $_POST['id_tel']);
                update_user_meta($user->ID, 'cellphone', $_POST['id_cellphone']);
                update_user_meta($user->ID, 'nacionalidade', $_POST['nacionalidade']);
                update_user_meta($user->ID, 'cep', $_POST['id_cep']);
                update_user_meta($user->ID, 'address', $_POST['id_end']);
                update_user_meta($user->ID, 'addressnumber', $_POST['id_endnumber']);
                update_user_meta($user->ID, 'addresscomplement', $_POST['id_endcomplement']);
                update_user_meta($user->ID, 'district', $_POST['id_district']);
                update_user_meta($user->ID, 'city', $_POST['id_city']);
                update_user_meta($user->ID, 'state', $_POST['id_state']);
                update_user_meta($user->ID, 'assoc', $_POST['id_assoc']);
                update_user_meta($user->ID, 'estilo', $_POST['id_estilo']);
                update_user_meta($user->ID, 'pratica', $_POST['id_pratica']);
                update_user_meta($user->ID, 'categoria', $_POST['id_modalidade']);

                $uploadedfile = $_FILES['avatar'];

                if($uploadedfile['error'] == 0 ){
                  $upload_overrides = array( 'test_form' => false );
                  $movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
                  if ( $movefile && ! isset( $movefile['error'] ) ) {
                      // echo "File is valid, and was successfully uploaded.\n";
                      // $filename should be the path to a file in the upload directory.
                      $filename = $movefile['file'];

                      // Check the type of file. We'll use this as the 'post_mime_type'.
                      $filetype = $movefile['type'];

                      // Get the path to the upload directory.
                      $wp_upload_dir = wp_upload_dir();

                      // Prepare an array of post data for the attachment.
                      $attachment = array(
                      	'guid'           => $wp_upload_dir['url'] . '/' . basename( $filename ),
                      	'post_mime_type' => $filetype,
                      	'post_title'     => preg_replace( '/\.[^.]+$/', '', basename( $filename ) ),
                      	'post_content'   => '',
                      	'post_status'    => 'inherit'
                      );

                      // Insert the attachment.
                      $attach_id = wp_insert_attachment( $attachment, $filename, $parent_post_id );

                      update_user_meta( $user->ID, 'avatar_id', $attach_id );
                    } else {
                        /**
                         * Error generated by _wp_handle_upload()
                         * @see _wp_handle_upload() in wp-admin/includes/file.php
                         */
                        echo $movefile['error'];

                        return;
                    }
                }

                echo '<div id="alerts" class="sucess">Perfil Atualizado</div>';
            }
            $user = wp_get_current_user();
            $birth = date_create_from_format('d/m/Y', get_the_author_meta('birthday', $user->ID));
            $birth = get_etaria_user(date_format($birth, 'Y-m-d'));
            update_user_meta($user->ID, 'fEtaria', $birth);
            ?>
	    <form action="<?php echo get_permalink($pages_ids['editar-perfil']);?>" method="post" enctype="multipart/form-data" encoding="multipart/form-data">
                    <div class="clear">
                        <label for="id_name"><b>Nome</b><br>
                            <input type="text" name="id_name" value="<?php echo $user->display_name; ?>">
                        </label>
                        <label for="id_password"><b>Senha Nova</b><br>
                            <input type="password" id="id_password" name="id_password" value="">
                        </label>
                        <label for="confirm_password"><b>Confirmar Senha Nova</b><br>
                            <input type="password" id="confirm_password" name="confirm_password" value="">
                            <div id="confirm" class="hide"></div>
                        </label>
                        <label for="id_mail"><b>Email</b><br>
                            <input type="email" name="id_mail" value="<?php echo $user->user_email; ?>">
                        </label>
                        <label for="id_tel"><b>Telefone</b><br>
                            <input type="text" id="phone" name="id_tel" value="<?php echo get_the_author_meta('phone', $user->ID); ?>">
                        </label>
                        <label for="id_tel"><b>Celular</b><br>
                            <input type="text" id="cellphone" name="id_cellphone" value="<?php echo get_the_author_meta('cellphone', $user->ID); ?>">
                        </label>
                        <div class="row-fluid">
                          <?php $pais = get_the_author_meta( 'nacionalidade', $user->ID ); ?>
                          <label for="nacionalidade" class="alignleft"><b>Nacionalidade</b><br>
                            <select class="" name="nacionalidade" id="nacionalidade">
                              <option value="">Selecione um País</option>
                              <option value="br" <?php selected( $pais, 'br'); ?>>Brasil</option>
                              <option value="py" <?php selected( $pais, 'py'); ?>>Paraguai</option>
                              <option value="ra" <?php selected( $pais, 'ra'); ?>>Argentina</option>
                            </select>
                          </label>
                          <label for="cep" class="alignleft margin-10"><b>CEP/Zip Code</b><br>
                              <input type="text" name="id_cep" id="cep" class="input-medium" value="<?php echo get_the_author_meta('cep', $user->ID); ?>">
                          </label>
                        </div>
                        <label for="id_end"><b>Endereço</b><br>
                            <input type="hidden" id="Aaddress" value="<?php echo get_the_author_meta('address', $user->ID); ?>">
                            <input type="text" id="address" name="id_end" val="<?php echo get_the_author_meta('address', $user->ID); ?>" readonly>
                        </label>
                        <label for="id_endnumber" class="alignleft"><b>Número</b><br>
                            <input type="text" name="id_endnumber" class="input-small" value="<?php echo get_the_author_meta('addressnumber', $user->ID); ?>">
                        </label>                        <label for="id_endcomplement" class="alignleft margin-10"><b>Complemento</b><br>                            <input type="text" name="id_endcomplement" class="input-small" value="<?php echo get_the_author_meta('addresscomplement', $user->ID); ?>">                        </label>                        <div class="clearfix">

                        </div>
                        <label for="id_district"><b>Bairro</b><br>
                            <input type="hidden" id="Adistrict" value="<?php echo get_the_author_meta('district', $user->ID); ?>">
                            <input type="text" id="district" name="id_district" val="<?php echo get_the_author_meta('district', $user->ID); ?>" readonly>
                        </label>
                        <label for="id_city"><b>Cidade</b><br>
                            <input type="hidden" id="Acity" value="<?php echo get_the_author_meta('city', $user->ID); ?>">
                            <input type="text" id="city" name="id_city" val="<?php echo get_the_author_meta('city', $user->ID); ?>" readonly>
                        </label>
                        <label for="id_state"><b>Estado</b><br>
                            <input type="hidden" id="Astate" value="<?php echo get_the_author_meta('state', $user->ID); ?>">
                            <input type="text" id="state" name="id_state" val="<?php echo get_the_author_meta('state', $user->ID); ?>" readonly>
                        </label>
                        <label for="avatar"><b>Avatar</b><br>
                          <?php if(get_the_author_meta('avatar_id', $user->ID)){ ?>
                              <img src="<?php echo wp_get_attachment_url( get_the_author_meta('avatar_id', $user->ID) ) ?>" class="img-responsive avatar" alt="Avatar" />
                          <?php  } ?>
                          <input type="file" name="avatar" class="margin-10" id="avatar" value="">
                        </label>
                    </div>
                    <div class="input-submit-fix">
                        <input type="submit" class="btn btn-primary fp-button" value="Atualizar Perfil">
                        <a href="<?php echo get_permalink($pages_ids['perfil']);?>" class="btn fp-button">Voltar</a>
                    </div>
        </form>

    </div>
            </div>
    <?php do_action( '__after_content' ); ?>
</section>
